[tox]
isolated_build = True
envlist =
    py314
    py313
    py312
    py311
    py310
    py39
;    py38
;    isort
;    pylint

[testenv]
deps =
    uv
package = skip
commands_pre =
    uv sync --active --group dev --locked --inexact
commands =
    uv run --active --no-sync pytest tests
;    uv run --active --no-sync python -m http.server 8888 -d tests/resources/local_server &
;    cd tests/local_tests
;    uv run --active --no-sync pytest local_test_*
    uv run --active --no-sync secretscraper --version

[testenv:isort]
deps =
    uv
package = skip
changedir = {toxinidir}
commands_pre =
    uv sync --active --group dev --locked --inexact
commands =
    uv run --active --no-sync isort .
    ;--check-only --diff

[testenv:pylint]
deps =
    uv
package = skip
changedir = {toxinidir}
commands_pre =
    uv sync --active --group dev --locked --inexact
commands =
    uv run --active --no-sync pylint tests src
